ANIMATION_SPEED = 0.1
BACKGROUND_IMAGE = 'OOP/assets/background.png'
CROW_ENEMY_SPEED = 2
ENEMY_IMAGE_PATH = 'OOP/assets/enemy.png'
ENEMY_SIZE = (50, 50)
FPS = 60
HEIGHT = 780
OBJECT_IMAGE_PATH = 'OOP/assets/object.png'
OBJECT_SIZE = (30, 30)
PATROL_ENEMY_SPEED = 2
SLIME_IMAGE_PATH = 'OOP/assets/slime.png'
SPEED = 5
VERTICAL_ENEMY_SPEED = 2
WIDTH = 1550
background_color = (200, 235, 255)
background_color_2 = '#B6FEFF'
slime_size = (60, 60)
spawn_interval = 1
